### ISSUE TITLE
倉庫のアプリ　注文の画面

### ISSUE THREAD

**Issue by maruito** [DecodeLLC/stuffy-web#23]
注文の画面　【発注番号　資材名】　→　【資材名　数量】　に変更可能ですか？
数量よりも入荷日のほうがいいですかね？
倉庫の人は発注番号の管理はいらないので、違う項目にしたいです。

**Comment by take-iwa** [comment]
アプリ画面での表示項目が、着荷日・糸種名・運送会社であること確認しました。
