### ISSUE TITLE
受注者でも管理画面や他の業者への注文情報が閲覧できてしまう

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/stuffy-web#39]
今のところ、受注者でも全て閲覧できてしまっています。

まず、受注者は受注者画面だけ見られるようにお願いします。

次に、受注者は自分の会社だけの注文情報を閲覧できるように修正お願いします。

**Comment by take-iwa** [comment]
@alexeypolitov パーミング確認しましたが、効いてない感じです。
受注者画面はchromeのシークレットウィンドウで確認してます。

下の例でいくと、受注者側(東レ㈱テト長・ナイ長)では、「118024」と「118022」だけが見られるはずですよね？

本番環境　受注者テストアカウント
u7fh9e1ireb2@sute.jp/d6zT0i7Y

↓管理画面＞ユーザー
<img width="443" alt="2017-07-25 17 53 07" src="https://user-images.githubusercontent.com/23730555/28564044-c140ff82-7162-11e7-8420-95e40c05e2e1.png">

↓管理者＞注文
<img width="679" alt="2017-07-25 17 53 35" src="https://user-images.githubusercontent.com/23730555/28564094-e26b3f6a-7162-11e7-8695-f153fa45932a.png">

↓受注者＞注文
<img width="821" alt="2017-07-25 17 54 12" src="https://user-images.githubusercontent.com/23730555/28564121-f3e20152-7162-11e7-83f2-327c874a4903.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください

**Comment by take-iwa** [comment]
確認しました！OKです。
