### ISSUE TITLE
受注者の予定・発送入力通知メール

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/stuffy-web#42]
受注者で予定を入れると通知メールでは「発送」になり、
発送を入力するとメールでは「予定」となっているので直して欲しい。

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
タイトル確認しました。
すみません。思い出しました。
内容で逆になっています。
<img width="165" alt="_2017-08-30_15_59_41" src="https://user-images.githubusercontent.com/23730555/29859372-bcc99440-8d9c-11e7-9697-b8d938195de2.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました

**Comment by take-iwa** [comment]
逆にする修正確認しました。
内容で、予定（１）は消したはずなのに、メールには残っています。

<img width="184" alt="_2017-08-30_16_12_01" src="https://user-images.githubusercontent.com/23730555/29859735-7a775788-8d9e-11e7-8ef9-4ba4d1d87e0a.png">

**Comment by alexeypolitov** [comment]
@take-iwa 修正しました。ご確認ください
