### ISSUE TITLE
新規注文のはずが、ステータスが「到着済み」になってしまうことがある

### ISSUE THREAD

**Issue by take-iwa** [DecodeLLC/stuffy-web#43]
まだ発送していない注文なのに、ステータスが「到着済み」になってしまっている。
アクセスのデータを確認してもらいましたが、余計なデータは入れていないとのこと。

その注文に対して、予定入力して、修正しようとした時、次のエラーが出たとのこと。
おそらく「到着済み」だから修正できなくなっています。

![2](https://user-images.githubusercontent.com/23730555/29442192-fd507fa6-840a-11e7-85a0-d1b1de0497d0.jpg)

**Comment by alexeypolitov** [comment]
@take-iwa 新しい注文でこういう問題は起きてますか？起きてるであれば注文番号を教えていただきたいです

**Comment by take-iwa** [comment]
@alexeypolitov 糸が入る前に注文区分Cを変えてしまったため発生してました。クローズします。
